### ISSUE TITLE
.focus(), .click(), etc fail on custom elements

### ISSUE THREAD

**Issue by cristinecula** [JaySunSyn/cypress-daywalker#1]
First of all, thank you for starting this project!
Doing acceptance tests for apps with custom elements is a real pain.

I took your plugin for a spin and quickly run into this issue:
![2019-04-12-100239_837x685_scrot](https://user-images.githubusercontent.com/710155/56019511-7fb46e80-5d0d-11e9-83f7-e4c9b7e3d0d4.png)

I am fully aware that this error is to be expected at this stage. I just want to know if you think it's possible to make this work?

**Comment by JaySunSyn** [comment]
Thanks @cristinecula!

I've added commands and an example here https://github.com/JaySunSyn/cypress-daywalker/blob/master/example/cypress/integration/example.spec.js#L43 and published v0.0.4

```
cy.get('my-el').call('close')
cy.get('my-el').dispatch('click')
```
Feel free to re-open if it's not solved

**Comment by cristinecula** [comment]
Thanks @JaySunSyn!
Works OK!

**Comment by JaySunSyn** [comment]
Nice
