### ISSUE TITLE
Failed to construct 'HTMLElement': Please use the 'new' operator

### ISSUE THREAD

**Issue by chrismclarke** [JaySunSyn/cypress-daywalker#11]
Injecting script from CDN using Angular 8 (Ionic 4 webcomponents).

Appears to be an issue with angular/custom elements (https://github.com/angular/angular/issues/24556).

Solution suggests ensure tsconfig set to target es2015, however I found I also needed to inject `custom-elements-es5-adapter` script after injecting daywalker. i.e.

```
      const script1 = w.document.createElement("script");
      script1.src =
        "https://cdn.jsdelivr.net/gh/jaysunsyn/cypress-daywalker@0.1.1/cypress-daywalker.js";
      const script2 = w.document.createElement("script");
      script2.src =
        "https://unpkg.com/@webcomponents/webcomponentsjs@2.0.3/custom-elements-es5-adapter.js";
      w.document.querySelector("head").appendChild(script1);
      w.document.querySelector("head").appendChild(script2);
```

So likely not a bug in daywalker, but might be of use to others

**Comment by JaySunSyn** [comment]
Thanks for reporting. Closing it but might be useful to others.
