### ISSUE TITLE
cannot find element in shadow dom

### ISSUE THREAD

**Issue by eiswind** [JaySunSyn/cypress-daywalker#4]
I just try to get started with daywalker.

I have a vaadin-text-field with an id. Inside of that custom element I need to type into a textfield of the shadow dom. When I try

cy.get('#nameField input').type("TEST")

it does not find the input. I guess I am getting something completely wrong and really would appreciate a little help :)

CypressError: Timed out retrying: Expected to find element: '#nameField input', but never found it.

I added daywalker like suggested in support/commands.js

**Comment by JaySunSyn** [comment]
I've added an additional example here: https://github.com/JaySunSyn/cypress-daywalker/blob/master/example/cypress/integration/example.spec.js#L32

```
cy.get('#nameField').setProp("TEST"); // sets the value property of vaadin-text-field
```

or

```
cy.get('vaadin-text-field input').setProp("TEST"); // sets the value of the native input
```
Does this work?

If not, could you paste your html?


I need to add clear documentation; Will do that as soon as I find some time...

**Comment by eiswind** [comment]
With 

`cy.get('#nameField').setProp("TEST")`

I get 'cannot read property 'store' of undefined.

What if I want to get all the events of typing into the field? Is there a chance that I can do an actual .type() on the input?

**Comment by JaySunSyn** [comment]
Is there a way you can share (or isolate) your code? 

(I would need to overwrite the type command to make it work, will look into that asap)

**Comment by eiswind** [comment]
https://github.com/eiswind/mastering-vaadin-flow-book/tree/cypress

it is in the 04-c module on the cypress branch

**Comment by JaySunSyn** [comment]
I didn't run it but try this and let me know pls.

```
describe('Comic character test', function () {

    before(() => {
        cy.visit('http://localhost:8080/character')
      });

    it('Opens the Character form', function () {
        cy.get('#nameField').setProp("TEST")
    })
})
```

**Comment by eiswind** [comment]
It seems that it cannot load the js file

:8080/node_modules/cypress-daywalker/cypress-daywalker.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)

looks more like a cypress issue with java/spring apps then?

but what looks VERY confusing is that i see output from daywalker in the test report.

**Comment by JaySunSyn** [comment]
Is `:8080/node_modules/` the location of your node_modules?

**Comment by JaySunSyn** [comment]
Pls join https://gitter.im/cypress-daywalker/ 
Might be a better medium to debug

**Comment by JaySunSyn** [comment]
Please confirm if this is still the case with version `0.2.1`

**Comment by JaySunSyn** [comment]
Closing this for now, tests are succeeding consistently  now as per https://travis-ci.com/JaySunSyn/cypress-daywalker/builds/.

Feel free to re-open.
